linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - typecheck

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gofmt:
    simplify: true

run:
  deadline: 5m
  skip-dirs:
    - vendor
    - third_party

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
